// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcRcYnd4uP-hPbnJuNDJ7wl4ZNqjod2TE',
    appId: '1:830841362138:web:89c8b76c4999062e00f7e3',
    messagingSenderId: '830841362138',
    projectId: 'silvocarbon',
    authDomain: 'silvocarbon.firebaseapp.com',
    storageBucket: 'silvocarbon.appspot.com',
    measurementId: 'G-EHG2ZSG1WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwsiJ4atJ3Aq2RP3eml1o1Z7lVodTJaVc',
    appId: '1:830841362138:android:c1fff89ac2595bfb00f7e3',
    messagingSenderId: '830841362138',
    projectId: 'silvocarbon',
    storageBucket: 'silvocarbon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxsmSYjfzqc-GxIRsre9-Ban82G6j0tg',
    appId: '1:830841362138:ios:eba8cddcb47c427c00f7e3',
    messagingSenderId: '830841362138',
    projectId: 'silvocarbon',
    storageBucket: 'silvocarbon.appspot.com',
    iosBundleId: 'com.idios.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxsmSYjfzqc-GxIRsre9-Ban82G6j0tg',
    appId: '1:830841362138:ios:815ae963a302831100f7e3',
    messagingSenderId: '830841362138',
    projectId: 'silvocarbon',
    storageBucket: 'silvocarbon.appspot.com',
    iosBundleId: 'com.idmacos.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcRcYnd4uP-hPbnJuNDJ7wl4ZNqjod2TE',
    appId: '1:830841362138:web:f678fb9a3dcb7d5a00f7e3',
    messagingSenderId: '830841362138',
    projectId: 'silvocarbon',
    authDomain: 'silvocarbon.firebaseapp.com',
    storageBucket: 'silvocarbon.appspot.com',
    measurementId: 'G-KHGZZ3QRRM',
  );

}